name: itech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.1.0
  http: ^1.2.1
  provider: ^6.1.2
  flutter_local_notifications: ^17.0.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_speed_dial: ^7.0.0
  lottie: ^3.1.2
  material_symbols_icons: ^4.2892.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/itech_green_drop.json
    - assets/certifications/emqxsl-ca.crt